services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chronica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./chronica-backend/prisma/schema.prisma:/docker-entrypoint-initdb.d/schema.prisma
    ports:
      - "15432:5432"
    networks:
      - chronica-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service (NestJS)
  backend:
    build:
      context: ./chronica-backend
      dockerfile: Dockerfile
      target: production
    container_name: chronica-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chronica-network
    volumes:
      - ./chronica-backend/prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        dumb-init node dist/main
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./chronica-frontend
      dockerfile: Dockerfile
      target: runner
    container_name: chronica-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chronica-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${FRONTEND_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

# Networks
networks:
  chronica-network:
    driver: bridge
    name: chronica-network

# Volumes
volumes:
  postgres_data:
    driver: local
    name: chronica-postgres-data
